### ISSUE TITLE
Python Bad Practices in separate repository?

### ISSUE THREAD

**Issue by Pablo2m** [halyph/mind-flow#116]
I have found your list very useful, have you considered putting it as a separate project? I don't know of any more (in fact I make several mistakes) but maybe at some point I can contribute some more.

**Comment by halyph** [comment]
Hello,

Please have a look into this section https://github.com/halyph/mind-flow/blob/master/2019/2019-09-30-python-bad-practices.md#original-sources, especially [wtfpython](https://github.com/satwikkansal/wtfpython)
I think those resources are much better structured. 

My list is only my personal findings, nothing more. And I believe **wtfpython** is the right place for contribution.

Regarding your question "have you considered putting it as a separate project?". No, I don't consider doing this. I see no value based on what I said above.
