### ISSUE TITLE
How to remove BlueJeans from MacOS

### ISSUE THREAD

**Issue by halyph** [halyph/mind-flow#76]
https://news.ycombinator.com/item?id=20394380
https://support.bluejeans.com/s/article/Cleanup-Process-for-the-BlueJeans-App

**Comment by halyph** [comment]
https://support.bluejeans.com/s/article/Cleanup-Process-for-the-BlueJeans-App

**Comment by halyph** [comment]
# BlueJeans Launcher Service

[Source](https://support.bluejeans.com/s/article/BlueJeans-Detector-Service "Permalink to BlueJeans Launcher Service")

BlueJeans Launcher Service – What Does It Do and Why Is It Necessary?

You may have noticed a BlueJeans service running on your Mac or Windows device, even when the BlueJeans App is closed. The BlueJeans service is called our "Launcher Service" and it is aimed at providing the best Join Flow experience for new and returning users. Below are more details on how it works.

**What Does It Do?**

The BlueJeans Launcher Service runs on a user’s computer and is only accessible within that computer itself. This service can be accessed by the BlueJeans webpage upon meeting join (when users click on a join URL). It has a few purposes:

* **Determine if the BlueJeans desktop application is already installed**. This allows us to offer a new installation or launch the existing app based on the user's machine. Alternative solutions in the industry have to offer both options – Install or Launch the App... which we've found can confuse end users.
* **Launch the BlueJeans desktop application into a meeting without prompting the user with confusing browser dialogs**. This allows meetings to launch quickly on one click without requiring any additional user interaction. It also prevents the user from making a wrong decision on a browser dialog which might permanently lock them out of launching meetings.
* **Secure the BlueJeans App**. The service allows us to ensure that only authorized web sites can launch the BlueJeans application.

**What Does It Look Like?**

The BlueJeans Launcher Service is a Localhost loopback address, such as (<http://localhost:18171/>) or ([http://127.0.0.1:18171](http://127.0.0.1:18171/)).

**Why Is It Necessary?**

Mobile operating systems (Android and iOS) have long had great support for launching native applications from web sites through so-called universal links. Sadly, desktop operating systems (Mac and Windows) still have not caught up on this front.

First, there is no cross-browser, built-in way for a website to be aware if the user has a specific desktop application installed, nor is there a way for the website to gracefully handle if it is not installed. This means that without a launcher service, a website cannot easily choose to offer installation instructions instead of launching the application in the appropriate case. It is worth noting some browsers do have ways to do this, but this does not work in every major browser.

Secondly, all modern browsers require approval from the user before allowing a website to launch a native application. This is a sensible precaution because allowing any website to launch any native program would be a huge security hole. This has been solved on mobile platforms by limiting mobile application launches to a specific website associated with this application, but sadly desktop platforms do not support this.

Because of the above, an approval dialog is necessary. However, this dialog is an annoyance to the user at best, and at worst may scare the user into denying a legitimate request.

To avoid this and provide a superior user experience, instead of directly launching the application, the website communicates with the already-running Launcher Service, which launches the app on its behalf. This process allows us to avoid the confusing security dialog shown by the browser and all of the disadvantages that come with it. Furthermore, we are able to do custom validation in the Launcher Service which allows us to ensure that only authorized websites can launch the BlueJeans application.

**Performance Considerations**

As stated above, the Launcher Service responds to requests from the BlueJeans webpage. As such, it does nothing except listen for network requests. A request is made only when the user tries to join a meeting. The Launcher Service responds within milliseconds, after which it goes back to doing nothing. This should have no noticeable impact on performance for a users machine, given the single simple task it performs.

**What Would It Look Like Without the Launcher Service?**

To understand all of the above more completely, let us discuss what happens without the use of a Launcher Service

First, let’s look at the case where the user tries to join a meeting but doesn’t already have the desktop application. The user would get a page in Safari and Firefox with the following:

"If nothing prompts from the Browser, download and run the App"

The webpage is unsure whether the application is installed and has to try to launch it AND offer a download at the same time. Too many options can lead to user confusion.

It should be noted that Chrome offers more advanced options for users to immediately be instructed to install applications. However, working well in only one browser is not acceptable to BlueJeans.

Compare what happens for the same scenario with the Launcher Service. Upon visiting the page, in any browser, BlueJeans correctly and reliably detects the user needs to download the app, and starts the download without any further user interaction, including providing browser-specific instructions on how to finish the installation.

 ![](https://support.bluejeans.com/servlet/rtaImage?eid=ka12R000000g0F7&feoid=00N44000006xJka&refid=0EM44000000J2yT)

Now, let’s move on to the more common use case, where the user already has the app installed. Without the Launcher Service, what happens when the user again tries to join a meeting?

 ![](https://support.bluejeans.com/servlet/rtaImage?eid=ka12R000000g0F7&feoid=00N44000006xJka&refid=0EM44000000J2yR)

As you can see, the user is required to click on an additional popup to allow the meeting to launch. The user may accidentally cancel this dialog and then be confused as to why nothing happened. Alternately, some users may not even notice the dialog and simply sit at this screen, confused.

On top of that, an additional click may seem not so bad, but if the user is frequently joining meetings, this adds significant friction to the launch experience. In Chrome, as shown, the user can elect to “Always Allow” but this option is not available in every browser (for example in Safari).

Compare what happens for the same scenario when the launcher service is used:

 ![](https://support.bluejeans.com/servlet/rtaImage?eid=ka12R000000g0F7&feoid=00N44000006xJka&refid=0EM44000000J2yV)

The user sees this page for a split second, and then the app launches, and the user is placed into the meeting with zero additional clicks.

Furthermore, since the Launcher Service is performing the launch, it performs additional checks to ensure launches can only be done from an authorized domain, so this cannot be abused to launch the app maliciously for spying purposes.

Finally, a big issue we can see without the launcher service is users who already have the App installed can download it a second time due to a variety of reasons: browser cache was cleared, incognito mode, the App was pushed out through a central IT deployment, etc. An unnecessary additional download can be very annoying to users and add confusion and delay when trying to join a meeting.

All of the reasons above have lead to issues in the past where users have been late or unable to join meetings at all. The launcher service has helped resolve this.

**Is the Launcher Service Secure?**

From the beginning, our launcher service was implemented with security as top of mind. The launcher service ensures that only BlueJeans-authorized websites (e.g. [bluejeans.com](http://bluejeans.com/)) can launch the BlueJeans desktop app into a meeting. Malicious websites cannot launch the BlueJeans desktop app into meetings, ensuring security and privacy.

**Summary**

Hopefully, this article helps explain why BlueJeans has chosen to use a Launcher Service to assist with desktop application installation detection and launch. BlueJeans has put a great deal of thought into this problem. We care deeply about user experience and want users to be able to get into meetings, whether it is their 1st or 100th meeting, as fast as possible without any friction. We also built the launcher with security and privacy being top of mind, so we can continue to be the meeting solution that both end users and IT teams trust.

For customers who still have concerns with users running the launcher service, you can [contact our Support Team](https://support.bluejeans.com/s/contactsupport) who can work with you to disable the launcher.

**Comment by halyph** [comment]
```bash
$ cat ~/Library/LaunchAgents/com.bluejeansnet.BlueJeansHelper.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.bluejeansnet.BlueJeansHelper</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Applications/BlueJeans.app/Contents/Resources/daemon/BlueJeansHelper.app/Contents/MacOS/BlueJeansHelper</string>
	</array>
	<key>KeepAlive</key>
	<true/>
</dict>
</plist>

```

**Comment by halyph** [comment]
![44A35563-1486-4D5F-8559-46DEA946027C](https://user-images.githubusercontent.com/241654/64465535-76d59680-d10d-11e9-80fb-c56b0c956b11.png)

**Comment by halyph** [comment]
```bash
$ launchctl list com.bluejeansnet.BlueJeansHelper
{
	"LimitLoadToSessionType" = "Aqua";
	"Label" = "com.bluejeansnet.BlueJeansHelper";
	"TimeOut" = 30;
	"OnDemand" = false;
	"LastExitStatus" = 9;
	"PID" = 31808;
	"Program" = "/Applications/BlueJeans.app/Contents/Resources/daemon/BlueJeansHelper.app/Contents/MacOS/BlueJeansHelper";
	"ProgramArguments" = (
		"/Applications/BlueJeans.app/Contents/Resources/daemon/BlueJeansHelper.app/Contents/MacOS/BlueJeansHelper";
	);
};
```

**Comment by halyph** [comment]
# Remove BlueJeans

1. remove the BlueJeans daemon

```bash
launchctl remove com.bluejeansnet.BlueJeansHelper rm ~/Library/LaunchAgents/com.bluejeansnet.BlueJeansHelper.plist
```

2. Remove `BlueJeans.app`

```bash
cd /Applications/
rm -rf BlueJeans.app/
```

3. Remove `~/Library/Application Support/Blue Jeans/` folder

**Comment by ShaunGriffithRyff** [comment]
I find this page very confusing. The title is "How to remove BlueJeans from MacOS", but it doesn't get to that until the bottom. Further, the last action is "rm -rf Blue\ Jeans/", but there is no space in that folder name. Also, I don't see how to get rid of the icon in the taskbar. I'm also disappointed that there's no direct way to do this. I think the first task after "build alpha version" is "Uninstall method". So I'm sorry, but I'm going to wait a few years before I try again.

**Comment by cr1ss4** [comment]
Thanks to halyph!
Guess what, after seeing (not reading) the long text I removed BlueJeans! If this is the only way to get rid of the helper it is the way to go.

**Comment by thirtified** [comment]
> ```shell
> rm -rf Blue\ Jeans/
> ```

It seems the path name has changed, you may also want to delete

```shell
rm -rf com.bluejeansnet.Blue
```

**Comment by cr1ss4** [comment]
Thanks, done

**Comment by anselanza** [comment]
> Because of the above, an approval dialog is necessary. However, this dialog is an annoyance to the user at best, and at worst may scare the user into denying a legitimate request.

Sounds better than installing a "helper" permanently on my computer - and a menu item by default! - for an app that I literally needed to use once.
